<template>
  <v-container fluid class="group-directory"><admin-hero title="Groups" description="Give people a shared purpose and the access to fulfil it." eyebrow="People & access" icon="mdi-account-group-outline"><template #actions><v-btn variant="text" prepend-icon="mdi-refresh" :loading="loading" :disabled="creating" @click="load">Reload directory</v-btn><v-btn v-if="directory?.canCreate" color="primary" variant="flat" prepend-icon="mdi-plus" @click="creating = true">Create group</v-btn></template></admin-hero>
    <nav class="group-directory-stats" aria-label="Group filters"><button v-for="stat in stats" :key="stat.key" :aria-pressed="kind === stat.key" @click="setKind(stat.key)"><span>{{ stat.title }}</span><strong>{{ stat.value }}</strong></button></nav>
    <section aria-labelledby="group-directory-title"><div class="group-heading"><div><span class="group-kicker">Access directory</span><h2 id="group-directory-title">Organized around responsibility</h2></div><router-link to="/users" class="text-body-small">Manage people <v-icon icon="mdi-arrow-right" size="16" /></router-link></div>
      <form class="group-directory-filters" @submit.prevent="searchNow"><v-text-field v-model="search" label="Search group name or purpose" prepend-inner-icon="mdi-magnify" variant="outlined" hide-details density="comfortable" clearable @update:model-value="queueSearch" /><v-btn v-if="search || kind !== 'all'" variant="text" @click="clearFilters">Clear filters</v-btn></form>
      <async-state v-if="loading" state="loading" title="Loading groups" message="Reading access policies and memberships." /><async-state v-else-if="error" state="error" title="The group directory is unavailable" :message="error" retry-label="Try again" @retry="load" /><async-state v-else-if="!directory?.items.length" state="empty" :title="search || kind !== 'all' ? 'No matching groups' : 'No groups to show'" message="Try another search or create a group around a shared responsibility." />
      <template v-else><ul class="group-register"><li v-for="group in directory.items" :key="group.id" class="group-register-row"><div class="group-register-identity"><router-link :to="groupLink(group.id)" class="group-register-name">{{ group.name }}<v-icon v-if="group.isSystem" icon="mdi-lock-outline" size="16" aria-label="System group" /></router-link><p class="group-register-purpose">{{ group.description || (group.id === 1 ? 'Full workspace administration and access to all content.' : group.id === 2 ? 'The policy applied to anonymous visitors.' : 'No purpose recorded yet.') }}</p><div class="group-register-meta"><span class="group-pill">{{ group.permissions.includes('manage:system') ? 'Full system access' : group.permissions.length + ' permissions' }}</span><span class="group-pill">{{ group.ruleCount }} page {{ group.ruleCount === 1 ? 'rule' : 'rules' }}</span><span v-if="group.isSystem" class="group-pill">System</span></div></div><div class="group-register-number"><strong>{{ group.memberCount }}</strong><span>{{ group.memberCount === 1 ? 'member' : 'members' }}</span></div><div class="group-register-number"><strong>{{ group.apiKeyCount }}</strong><span>active credentials</span></div><v-btn :to="groupLink(group.id)" variant="text" append-icon="mdi-arrow-right" class="group-register-action" :aria-label="'Manage ' + group.name">Manage</v-btn></li></ul><div class="group-pagination"><span aria-live="polite">{{ offset + 1 }}–{{ Math.min(offset + directory.items.length, directory.total) }} of {{ directory.total }} groups</span><div class="group-actions"><v-btn variant="text" :disabled="offset === 0" @click="paginate(-1)">Previous</v-btn><v-btn variant="text" :disabled="offset + directory.limit >= directory.total" @click="paginate(1)">Next</v-btn></div></div></template>
    </section><group-create ref="createForm" v-model="creating" @created="created" />
  </v-container>
</template>
<script lang="ts">
import AsyncState from '@/components/common/async-state.vue'
import GroupCreate from './admin-groups-create.vue'
import { fetchGroupDirectory } from '../../helpers/group-workspace-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
import type { GroupDirectory } from '../../../shared/group-policy.ts'
export default {
  components: { AsyncState, GroupCreate },
  data() { return { directory: null as GroupDirectory | null, search: '', kind: 'all', offset: 0, loading: false, error: '', creating: false, sequence: 0, disposed: false, timer: null as ReturnType<typeof setTimeout> | null } },
  computed: { stats() { return [{ key: 'all', title: 'All groups', value: this.directory?.counts.groups ?? '—' },{ key: 'administrative', title: 'Administrative', value: this.directory?.counts.administrative ?? '—' },{ key: 'empty', title: 'Without members', value: this.directory?.counts.empty ?? '—' },{ key: 'system', title: 'System identities', value: this.directory?.counts.system ?? '—' }] } },
  watch: { '$route.query': { immediate: true, handler() { const q = this.$route.query, search = typeof q.search === 'string' ? q.search : '', kind = typeof q.kind === 'string' && ['all','administrative','empty','system','custom'].includes(q.kind) ? q.kind : 'all', offset = /^\d+$/.test(String(q.offset ?? '')) ? Math.min(Number(q.offset), 1000000) : 0; if (this.directory && search === this.search && kind === this.kind && offset === this.offset) return; this.search = search; this.kind = kind; this.offset = offset; void this.load(false) } } },
  beforeUnmount() { this.disposed = true; this.sequence++; if (this.timer) clearTimeout(this.timer) },
  beforeRouteLeave() { return (this.$refs.createForm as { canLeave: () => boolean } | undefined)?.canLeave() ?? true },
  methods: {
    async load(sync = true) { const sequence = ++this.sequence; this.loading = true; this.error = ''; if (sync) { const query: Record<string,string> = {}; if (this.search) query.search = this.search; if (this.kind !== 'all') query.kind = this.kind; if (this.offset) query.offset = String(this.offset); void this.$router.replace({ query }) } try { const directory = await fetchGroupDirectory(new URLSearchParams({ search: this.search || '', kind: this.kind, offset: String(this.offset), limit: '25' })); if (!this.disposed && sequence === this.sequence) this.directory = directory } catch (error) { if (!this.disposed && sequence === this.sequence) this.error = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } },
    groupLink(id: number) { return { path: `/groups/${id}`, query: { from: this.$route.fullPath } } },
    queueSearch() { if (this.timer) clearTimeout(this.timer); this.timer = setTimeout(() => this.searchNow(), 250) }, searchNow() { if (this.timer) clearTimeout(this.timer); this.offset = 0; void this.load() }, setKind(kind: string) { this.kind = kind; this.searchNow() }, clearFilters() { this.search = ''; this.kind = 'all'; this.searchNow() }, paginate(direction: number) { this.offset = Math.max(0, this.offset + direction * 25); void this.load() }, created(id: number) { this.creating = false; void this.$router.push(this.groupLink(id)) }
  }
}
</script>
<style lang="scss" src="./group-workspace.scss"></style>
