import fs from 'node:fs'
import path from 'node:path'

describe('ordinary Wiki agent administration integration', () => {
  const read = relativePath => fs.readFileSync(path.join(process.cwd(), relativePath), 'utf8')
  const router = read('client/router.ts')
  const navigation = read('client/components/admin.vue')
  const page = read('client/components/admin/admin-agents.vue')
  const agentAdmin = read('client/components/agents/agent-admin.vue')
  const theme = read('client/components/admin/admin-theme.vue')
  const skillAdmin = read('client/components/agents/skill-admin.vue')
  const vite = read('vite.config.mts')
  const master = read('server/master.ts')

  test('registers Agents in the ordinary administration router and sidebar', () => {
    expect(router).toMatch(/path:\s*['"]\/agents['"][^\n]*admin-agents\.vue/)
    const catalog = fs.readFileSync(path.join(process.cwd(), 'client/helpers/admin-navigation.ts'), 'utf8')
    expect(catalog).toMatch(/key: 'agents',[\s\S]*?to: '\/agents',[\s\S]*?permission: 'manage:system'/)
    expect(navigation).toContain('buildAdminNavigation')
    expect(navigation).toMatch(/admin:agents\.title/)
    expect(navigation).toMatch(/this\.\$route\.path === '\/agents'[^]*admin:agents\.title/)
  })

  test('embeds the complete administration console with ordinary session CSRF', () => {
    expect(page).toMatch(/AgentAdmin[^\n]*:csrf-token=['"]csrfToken['"][^\n]*embedded/)
    expect(page).toMatch(/const csrfToken = siteConfig\.agentCsrfToken/)
    expect(page).toMatch(/AgentAdmin\(v-if='agentsEnabled'/)
    expect(page).toMatch(/const agentsEnabled = siteConfig\.agentsEnabled/)
    expect(page).toMatch(/Agents are not enabled/)
  })

  test('uses the compact shared administration hero for Agents and Theme', () => {
    expect(page).toMatch(/AdminHero\([^]*title='Agents are not enabled'[^]*heading-id='agents-disabled-title'/)
    expect(page).toMatch(/AdminHero\([^]*template\(#status\)/)
    expect(page).not.toMatch(/admin-agents__disabled-(?:mark|copy)/)
    expect(agentAdmin).toContain('<AdminHero')
    expect(agentAdmin).toContain('<template #status>')
    expect(agentAdmin).toContain('<template #actions>')
    expect(agentAdmin).toMatch(/description="Connect models, curate expertise, and shape how agents work with your knowledge\."/)
    expect(agentAdmin).not.toContain('<header class="agent-hero">')
    expect(agentAdmin).not.toContain('agent-docket')
    expect(agentAdmin).not.toMatch(/min-height:\s*calc\(var\(--wiki-space-12\) \* 5\)/)

    expect(theme).toMatch(/AdminHero\([^]*heading-id='admin-theme-title'/)
    expect(theme).toMatch(/template\(#status\)[^]*Unsaved changes[^]*Theme up to date/)
    expect(theme).toMatch(/template\(#actions\)[^]*@click='save'/)
    expect(theme).not.toContain('.admin-header')
  })

  test('includes setup, connections and memory alongside operational administration', () => {
    expect(agentAdmin).toMatch(/value="runtime"[^]*value="profiles"[^]*value="skills"[^]*value="browser"/)
    expect(agentAdmin).toMatch(/role="tab"[^]*:tabindex="tab === section\.value \? 0 : -1"/)
    expect(agentAdmin).toContain('value="overview"')
    expect(agentAdmin).toContain('value="tools"')
    expect(agentAdmin).toContain('value="memory"')
  })

  test('derives Agent-only protocol behavior and group-scoped capability access', () => {
    expect(agentAdmin).toMatch(/Protocol-derived behavior/)
    expect(agentAdmin).toMatch(/label="Tool calling"/)
    expect(agentAdmin).toMatch(/Native API tools/)
    expect(agentAdmin).toMatch(/Prompt-emulated tools/)
    expect(agentAdmin).toMatch(/Prompt-emulated; one action per model turn/)
    expect(agentAdmin).toMatch(/agentProviderProtocolExecutionModes\(option\.value\)\.includes\('agent'\)/)
    expect(agentAdmin).toMatch(/policies: \{ allowedModes: \['agent'\]/)
    expect(agentAdmin).toMatch(/Advanced limits and quotas/)
    expect(agentAdmin).toMatch(/request<GroupOption\[]>\(\s*['"]\/_api\/groups['"]\s*,\s*\{\s*signal:\s*controller\.signal\s*\}\s*\)/)
    expect(skillAdmin).toMatch(/request\(\s*['"]\/_api\/groups['"][^)]*\)/)
    expect(agentAdmin).not.toMatch(/request<GroupOption\[]>\(\s*['"]\/api\/groups['"]\s*\)/)
    expect(skillAdmin).not.toMatch(/request\(\s*['"]\/api\/groups['"]\s*\)/)
    expect(agentAdmin).not.toMatch(
      /label="(?:Parallel functions|Agent mode|Generation-only mode|Capability revision|Pricing revision|Structured output|Usage reporting)"/
    )
    expect(agentAdmin).toMatch(/value="profiles"[^>]*>[\s\S]*Providers[\s\S]*Models and access/)
    expect(agentAdmin).toMatch(/profileStep === 'models'[\s\S]*Assign model roles/)
    expect(agentAdmin).toMatch(/v-model="profileDraft\.model"[^\n]*label="Agent model"/)
    expect(agentAdmin).toMatch(/v-model="profileDraft\.utilityModel"[^\n]*label="Utility model \(optional\)"/)
    expect(agentAdmin).toMatch(/title="Set global default"[^\n]*subtitle="Makes this the workspace fallback"/)
    expect(agentAdmin).toMatch(/runtime\?\.providerEnabled !== true/)
    expect(agentAdmin).toMatch(/Provider administration is unavailable while provider inference is disabled/)
    expect(agentAdmin).toMatch(/profileError/)
    expect(agentAdmin).toMatch(/v-model="profileDraft\.secretValue"[^\n]*label="API key"[^\n]*type="password"/)
    expect(agentAdmin).toMatch(/Encrypted with the server-managed provider key and never returned/)
    expect(agentAdmin).toMatch(/secretReference: null, \.\.\.\(profileDraft\.secretValue \? \{ secretValue: profileDraft\.secretValue \} : \{\}\)/)
    expect(agentAdmin).toMatch(/:title="profile\.status === 'disabled' \? 'Test and enable' : 'Test connection'"/)
    expect(agentAdmin).toMatch(/:disabled="!profile\.secretConfigured \|\| Boolean\(actionBusyKey\)"/)
    expect(agentAdmin).toMatch(/@click="testConnection\(profile\)"/)
    expect(agentAdmin).toMatch(/connection-check[^]*enableOnSuccess: profile\.status === 'disabled'/)
    expect(agentAdmin).toMatch(/title="Enable provider"/)
    expect(agentAdmin).toMatch(/:disabled="!profile\.conformed \|\| !profile\.secretConfigured \|\| Boolean\(actionBusyKey\)"/)
    expect(agentAdmin).toMatch(/@click="confirmEnableProfile\(profile\)"/)
    expect(agentAdmin).toMatch(/Enablement review[^]*willBecomeDefault\(enablingProfile\)/)
    expect(agentAdmin).toMatch(/Wiki verifies the provider connection automatically after every save/)
    expect(agentAdmin).toMatch(/Edit settings[^]*Updates this profile/)
    expect(agentAdmin).toMatch(/v-model="grantDraft\.groupIds"[^]*item-title="name"/)
    expect(agentAdmin).toMatch(/!grantsDirty/)
    expect(agentAdmin).toMatch(/Save and clear default/)
    expect(agentAdmin).toMatch(/Saving any access change clears this profile as the global default/)
    expect(agentAdmin).toMatch(/profileDraftValid/)
    expect(agentAdmin).toMatch(/providerBaseUrlError/)
    expect(agentAdmin).toMatch(/Discard provider changes/)
    expect(agentAdmin).toMatch(/Network allowlist review/)
    expect(agentAdmin).toMatch(/Use the exact canonical URL/)
    expect(agentAdmin).toMatch(/Add and allow target/)
    expect(agentAdmin).toMatch(/This is the global default\. Removing it leaves new conversations without a default/)
    expect(agentAdmin).toMatch(/Refresh failed · showing last loaded status/)
    expect(agentAdmin).not.toMatch(/Group IDs|immutable profile|immutable version/)
    expect(agentAdmin).toMatch(/server-managed API keys are permanently deleted/)
  })

  test('has no isolated agent application or host routing', () => {
    expect(fs.existsSync(path.join(process.cwd(), 'client/agents-app.ts'))).toBe(false)
    expect(fs.existsSync(path.join(process.cwd(), 'client/index-agents.ts'))).toBe(false)
    expect(fs.existsSync(path.join(process.cwd(), 'server/views/agent.pug'))).toBe(false)
    expect(vite).not.toMatch(/index-agents/)
    expect(master).not.toMatch(/agentsPublicOrigin|agentVite|surface:\s*['"]embedded['"]/)
  })
})
