<template>
  <section aria-labelledby="group-members-heading"><div class="group-heading"><div><span class="group-kicker">Who shares this access</span><h2 id="group-members-heading">{{ candidates ? 'Add people to this group' : 'Members' }}</h2><p>{{ candidates ? 'Choose existing accounts, then review their new membership.' : 'A person’s access combines the policies of all their groups. Membership changes end their existing sign-in sessions.' }}</p></div><div class="group-actions"><v-btn v-if="candidates" variant="text" prepend-icon="mdi-arrow-left" @click="setMode(false)">Current members</v-btn><v-btn v-else-if="canManage" variant="outlined" prepend-icon="mdi-account-plus-outline" :disabled="disabled" @click="setMode(true)">Add members</v-btn></div></div>
    <v-alert v-if="disabled && canManage" type="info" variant="tonal" class="mb-4">{{ lockReason }}</v-alert>
    <form class="group-directory-filters" @submit.prevent="searchNow"><v-text-field v-model="search" :label="candidates ? 'Find an account to add' : 'Search current members'" variant="outlined" hide-details clearable prepend-inner-icon="mdi-magnify" @update:model-value="queueSearch" /><v-btn variant="text" :loading="loading" @click="load">Reload members</v-btn></form>
    <div v-if="selected.length" class="group-selection-bar"><strong>{{ selected.length }} selected</strong><v-btn variant="text" :disabled="disabled" @click="selected = []">Clear selection</v-btn><v-spacer /><v-btn :color="candidates ? 'primary' : undefined" variant="flat" :disabled="disabled" @click="$emit('review', { action: candidates ? 'add' : 'remove', people: selected })">{{ candidates ? 'Review additions' : 'Review removals' }}</v-btn></div>
    <async-state v-if="loading" state="loading" title="Loading membership" /><async-state v-else-if="error" state="error" title="Membership could not be loaded" :message="error" retry-label="Try again" @retry="load" /><async-state v-else-if="!directory?.items.length" state="empty" :title="search ? 'No matching accounts' : candidates ? 'No accounts available to add' : 'No members yet'" :message="search ? 'Try another name or email address.' : candidates ? 'Create accounts in Users, then add them here.' : 'Add people when this group’s access policy is ready.'" />
    <template v-else><ul class="group-member-list"><li v-for="person in directory.items" :key="person.id" class="group-member-row"><input v-if="canManage" type="checkbox" :aria-label="'Select ' + person.name" :checked="selected.some(item => item.id === person.id)" :disabled="disabled || !person.canRemove || (selected.length >= 100 && !selected.some(item => item.id === person.id))" @change="select(person, ($event.target as HTMLInputElement).checked)" /><div class="group-member-person"><router-link v-if="canReadAccounts" :to="'/users/' + person.id">{{ person.name }}</router-link><strong v-else>{{ person.name }}</strong><span>{{ person.email }}</span></div><div class="group-member-state"><span>{{ person.isActive ? 'Active account' : 'Inactive account' }}</span><small v-if="!person.canRemove">Protected membership</small></div><v-btn v-if="!candidates" variant="text" icon="mdi-shield-search" size="small" :aria-label="'Check access for ' + person.name" @click="$emit('evaluate', { id: person.id, name: person.name })" /></li></ul><div class="group-pagination"><span>{{ offset + 1 }}–{{ Math.min(offset + directory.items.length, directory.total) }} of {{ directory.total }}</span><div class="group-actions"><v-btn variant="text" :disabled="offset === 0" @click="paginate(-1)">Previous</v-btn><v-btn variant="text" :disabled="offset + 25 >= directory.total" @click="paginate(1)">Next</v-btn></div></div></template>
  </section>
</template>
<script lang="ts">
import AsyncState from '@/components/common/async-state.vue'
import { fetchGroupMembers } from '../../helpers/group-workspace-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
import type { GroupMembers, GroupMember } from '../../../shared/group-policy.ts'
export default {
  components: { AsyncState }, props: { groupId: { type: Number, required: true }, revision: { type: String, required: true }, disabled: Boolean, canManage: Boolean, canReadAccounts: Boolean, lockReason: { type: String, default: 'Save or reset the policy draft before changing membership.' } }, emits: ['review','evaluate'],
  data() { return { candidates: false, search: '', offset: 0, selected: [] as Array<{ id: number; name: string }>, directory: null as GroupMembers | null, loading: false, error: '', sequence: 0, disposed: false, timer: null as ReturnType<typeof setTimeout> | null } },
  watch: { groupId: { immediate: true, handler() { this.candidates = false; this.search = ''; this.offset = 0; this.selected = []; void this.load() } }, revision() { this.selected = []; void this.load() } },
  beforeUnmount() { this.disposed = true; this.sequence++; if (this.timer) clearTimeout(this.timer) },
  methods: { async load() { const sequence = ++this.sequence; this.loading = true; this.error = ''; try { const result = await fetchGroupMembers(this.groupId, new URLSearchParams({ search: this.search || '', candidates: String(this.candidates), limit: '25', offset: String(this.offset) })); if (!this.disposed && sequence === this.sequence) this.directory = result } catch (error) { if (!this.disposed && sequence === this.sequence) this.error = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } }, queueSearch() { if (this.timer) clearTimeout(this.timer); this.timer = setTimeout(() => this.searchNow(), 250) }, searchNow() { if (this.timer) clearTimeout(this.timer); this.offset = 0; void this.load() }, paginate(direction: number) { this.offset = Math.max(0, this.offset + direction * 25); void this.load() }, setMode(candidates: boolean) { this.candidates = candidates; this.selected = []; this.search = ''; this.offset = 0; void this.load() }, select(person: GroupMember, checked: boolean) { if (this.disabled || !this.canManage || !person.canRemove || (checked && this.selected.length >= 100 && !this.selected.some(item => item.id === person.id))) return; this.selected = checked ? [...this.selected.filter(item => item.id !== person.id), { id: person.id, name: person.name }] : this.selected.filter(item => item.id !== person.id) } }
}
</script>
