<template>
  <section aria-labelledby="group-access-heading"><div class="group-heading"><div><span class="group-kicker">Understand a decision</span><h2 id="group-access-heading">Access check</h2><p>Test a hypothetical public page against this group, or a member’s combined group policies.</p></div></div>
    <div class="group-access-layout"><form class="group-surface group-access-form" @submit.prevent="evaluate"><v-select v-model="scope" :items="[{ title: 'This group only', value: 'group' },{ title: 'A member’s combined groups', value: 'member' }]" label="Whose policy" variant="outlined" hide-details :disabled="loading" />
        <v-autocomplete v-if="scope === 'member'" v-model="memberId" v-model:search="memberSearch" :items="memberOptions" item-title="title" item-value="id" label="Current group member" variant="outlined" hide-details no-filter clearable :loading="memberLoading" :disabled="loading" @update:search="searchMembers" /><v-alert v-if="memberError && scope === 'member'" type="error" variant="tonal">{{ memberError }}<v-btn variant="text" @click="searchMembers">Try again</v-btn></v-alert>
        <v-select v-model="permission" :items="actions" label="Page action" variant="outlined" hide-details :disabled="loading" /><v-text-field v-model="path" label="Public page path" variant="outlined" hint="No leading /. This does not look up or disclose a real page." persistent-hint :disabled="loading" maxlength="500" /><div class="group-form-grid"><v-text-field v-model="locale" label="Language" variant="outlined" hide-details :disabled="loading" maxlength="24" /><v-combobox v-model="tags" label="Page tags" variant="outlined" hide-details multiple chips closable-chips :disabled="loading" /></div>
        <v-checkbox v-if="hasDraft" v-model="useDraft" label="Include this group’s unsaved policy" hide-details :disabled="loading" /><p v-else class="group-note">Uses the saved policy. Changes to a draft do not affect live access.</p><v-btn color="primary" variant="flat" type="submit" prepend-icon="mdi-shield-search" :loading="loading" :disabled="!valid">Check access</v-btn>
      </form><div class="group-access-output"><async-state v-if="loading" state="loading" title="Evaluating group access" /><async-state v-else-if="error" state="error" title="Access could not be checked" :message="error" retry-label="Try again" @retry="evaluate" /><div v-else-if="!result" class="group-access-intro"><v-icon icon="mdi-shield-search" size="36" /><h3>A result you can follow</h3><p>See which matching rules win and which ones are overridden. The same rule engine checks access in the wiki.</p></div>
        <template v-else><div class="group-access-result" :class="result.allowed ? 'is-allowed' : 'is-denied'"><span class="group-kicker">{{ result.source === 'draft' ? 'Draft policy evaluation' : 'Saved policy evaluation' }}</span><h3><v-icon :icon="result.allowed ? 'mdi-check-circle-outline' : 'mdi-minus-circle-outline'" />{{ result.allowed ? 'Allowed by group policy' : 'Denied by group policy' }}</h3><p>{{ result.reason }}</p><small>{{ result.subject }} · {{ checkedPermission }} · /{{ checkedPath }}</small></div><v-alert v-if="outdated" type="info" variant="tonal" class="my-4">Inputs or policy changed after this result. Run the check again.</v-alert><div class="group-heading mt-5 mb-3"><h3 class="text-title-small">Rule explanation</h3><span class="group-note">{{ result.ruleCount }} evaluated</span></div><p v-if="!result.rules.length" class="group-note">No page rules contributed to this check.</p><ol v-else class="group-access-rules"><li v-for="(rule, index) in result.rules" :key="rule.groupId + ':' + rule.ruleId + ':' + index"><span class="group-access-outcome" :class="{ 'is-winner': rule.outcome === 'winner' }">{{ outcomeTitles[rule.outcome] }}</span><div><strong>{{ rule.groupName }}</strong><span>{{ rule.deny ? 'Deny' : 'Allow' }} · {{ matchTitles[rule.match] }} <code>{{ rule.path || 'all paths' }}</code></span></div></li></ol><p v-if="result.rulesTruncated" class="group-note mt-3">Showing {{ result.rules.length }} of {{ result.ruleCount }} rules, with matching rules first. Every rule was evaluated.</p></template>
        <p class="group-access-boundary">This checks public-page permission rules. Private ownership, publication, account status, provider grants and feature-specific checks still apply. It does not grant access or change a page.</p>
      </div></div>
  </section>
</template>
<script lang="ts">
import { type PropType } from 'vue'
import AsyncState from '@/components/common/async-state.vue'
import { groupPermissions, type GroupPolicyDraft, type GroupAccessResult, type GroupAccessInput } from '../../../shared/group-policy.ts'
import { fetchGroupMembers, evaluateGroupPolicy, groupPolicySignature, groupPolicyCopy } from '../../helpers/group-workspace-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
export default {
  components: { AsyncState }, props: { groupId: { type: Number, required: true }, revision: { type: String, required: true }, draft: { type: Object as PropType<GroupPolicyDraft>, required: true }, hasDraft: Boolean, initialMember: { type: Object as PropType<{ id: number; name: string } | null>, default: null } },
  data() { return { scope: 'group', memberId: null as number | null, memberSearch: '', memberOptions: [] as Array<{ id: number; title: string }>, memberLoading: false, memberError: '', memberSequence: 0, memberTimer: null as ReturnType<typeof setTimeout> | null, permission: 'read:pages', path: 'home', locale: 'en', tags: [] as string[], useDraft: true, loading: false, error: '', result: null as GroupAccessResult | null, checkedSignature: '', checkedPermission: '', checkedPath: '', sequence: 0, disposed: false, actions: groupPermissions.filter(p => p.pageScoped).map(p => ({ title: p.title, value: p.key })), outcomeTitles: { winner: 'Highest-priority match', overridden: 'Overridden', 'no-match': 'Does not match', locale: 'Different language', permission: 'Different action' }, matchTitles: { START: 'Prefix', END: 'Suffix', EXACT: 'Exact path', REGEX: 'Regex', TAG: 'Tag' } } },
  computed: { valid(): boolean { return this.scope !== 'member' || this.memberId !== null }, signature(): string { return JSON.stringify([this.groupId, this.revision, this.scope, this.memberId, this.permission, this.path, this.locale, this.tags, this.hasDraft && this.useDraft ? groupPolicySignature(this.draft) : null]) }, outdated(): boolean { return Boolean(this.result && this.checkedSignature !== this.signature) } },
  watch: { initialMember: { immediate: true, handler(member: { id: number; name: string } | null) { if (member) { this.scope = 'member'; this.memberOptions = [{ id: member.id, title: member.name }]; this.memberId = member.id } } }, groupId() { this.sequence++; this.result = null; this.error = ''; this.memberSequence++; this.memberId = null; this.memberOptions = []; this.memberSearch = ''; this.scope = 'group' }, scope(value: string) { if (value === 'member') this.searchMembers() } },
  beforeUnmount() { this.disposed = true; this.sequence++; this.memberSequence++; if (this.memberTimer) clearTimeout(this.memberTimer) },
  methods: {
    async evaluate() { if (this.loading || !this.valid) return; const sequence = ++this.sequence, signature = this.signature, input: GroupAccessInput = { path: this.path.trim(), locale: this.locale.trim(), tags: [...this.tags], permission: this.permission, ...(this.scope === 'member' ? { memberId: this.memberId! } : {}), ...(this.hasDraft && this.useDraft ? { draft: groupPolicyCopy(this.draft) } : {}) }; this.loading = true; this.error = ''; try { const result = await evaluateGroupPolicy(this.groupId, input); if (!this.disposed && sequence === this.sequence) { this.result = result; this.checkedSignature = signature; this.checkedPath = input.path; this.checkedPermission = this.actions.find(action => action.value === input.permission)?.title ?? input.permission } } catch (error) { if (!this.disposed && sequence === this.sequence) this.error = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } },
    searchMembers() { if (this.memberTimer) clearTimeout(this.memberTimer); const sequence = ++this.memberSequence, search = this.memberSearch || ''; this.memberTimer = setTimeout(async () => { this.memberLoading = true; this.memberError = ''; try { const result = await fetchGroupMembers(this.groupId, new URLSearchParams({ search, limit: '25' })); if (!this.disposed && sequence === this.memberSequence) { const selected = this.memberOptions.find(item => item.id === this.memberId); this.memberOptions = result.items.map(person => ({ id: person.id, title: `${person.name} · ${person.email}` })); if (selected && !this.memberOptions.some(item => item.id === selected.id)) this.memberOptions.unshift(selected) } } catch (error) { if (!this.disposed && sequence === this.memberSequence) this.memberError = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.memberSequence) this.memberLoading = false } }, 250) }
  }
}
</script>
