<template>
  <v-container fluid class="account-workspace">
    <admin-hero :title="saved?.name || 'Account workspace'" :description="saved?.email || 'Identity, membership and account lifecycle.'" eyebrow="People & access" icon="mdi-account-outline"><template #actions><v-btn :to="directoryPath" variant="text" prepend-icon="mdi-arrow-left">All accounts</v-btn><v-btn variant="text" prepend-icon="mdi-refresh" :loading="loading" :disabled="busy || dialog" @click="reload">Reload account</v-btn></template></admin-hero>
    <v-alert v-if="notice" type="success" variant="tonal" closable class="mt-5" @click:close="notice = ''">{{ notice }}</v-alert>
    <async-state v-if="loading" state="loading" title="Opening the account workspace" />
    <async-state v-else-if="loadError" state="error" title="This account is unavailable" :message="loadError" retry-label="Try again" @retry="reload" />
    <template v-else-if="saved">
      <header class="account-identity"><div class="account-portrait" aria-hidden="true">{{ initials(saved.name) }}</div><div class="account-identity-name"><span class="account-eyebrow">Account #{{ saved.id }}{{ self ? ' · Your account' : '' }}</span><p>{{ saved.providerTitle }}</p></div><div class="account-identity-status"><span><i :class="{ paused: !saved.isActive }" />{{ saved.isActive ? 'Active account' : 'Inactive account' }}</span><small>{{ saved.isVerified ? 'Email verified' : 'Email unverified' }}</small></div></header>
      <div class="account-tabs-row"><div role="tablist" aria-label="Account workspace sections" class="account-tabs"><button v-for="tab in tabs" :id="`account-tab-${tab.key}`" :key="tab.key" role="tab" :aria-selected="section === tab.key" :aria-controls="`account-panel-${tab.key}`" :tabindex="section === tab.key ? 0 : -1" @click="setSection(tab.key)" @keydown="tabKey($event, tab.key)">{{ tab.title }}</button></div><span aria-live="polite">{{ dirty ? 'Unsaved profile changes' : 'Showing saved account' }}</span></div>
      <v-alert v-if="saved.capabilities.explanation" type="info" variant="tonal" class="mb-5">{{ saved.capabilities.explanation }}</v-alert>
      <section v-show="section === 'profile'" id="account-panel-profile" role="tabpanel" aria-labelledby="account-tab-profile">
        <div class="account-profile-layout"><div class="account-main-column"><section class="account-surface"><header><span class="account-eyebrow">Personal details</span><h3>The person behind the account</h3><p>Keep their name and contact information recognizable to your team.</p></header><div class="account-profile-form"><v-text-field v-model="draft.name" label="Display name" variant="outlined" maxlength="255" :disabled="profileLocked" /><v-text-field v-model="draft.email" label="Email address" type="email" variant="outlined" maxlength="255" :disabled="profileLocked" /><v-text-field v-model="draft.jobTitle" label="Role or job title" variant="outlined" maxlength="255" :disabled="profileLocked" /><v-text-field v-model="draft.location" label="Location" variant="outlined" maxlength="255" :disabled="profileLocked" /><v-text-field v-model="draft.timezone" label="Time zone" variant="outlined" hint="For example, Europe/London or UTC." persistent-hint :disabled="profileLocked" /></div><div v-if="emailChanged" class="account-impact-note"><v-icon icon="mdi-email-sync-outline" /><p>Changing the email address clears its verified status and ends this account’s sign-in sessions. Confirm the new address before marking it verified.</p></div></section>
          <section class="account-surface"><header><span class="account-eyebrow">Membership</span><h3>Access through belonging</h3><p>Permissions from these groups are combined. Page rules and private ownership still determine access to individual pages.</p></header><div class="account-membership-grid"><label v-for="group in saved.availableGroups" :key="group.id" :class="{ selected: draft.groups.includes(group.id), locked: profileLocked || self || !group.canAssign }"><input v-model="draft.groups" type="checkbox" :value="group.id" :disabled="profileLocked || self || !group.canAssign || (saved.id === 1 && group.id === 1)" /><span><strong>{{ group.name }}</strong><small>{{ group.permissions.length }} {{ group.permissions.length === 1 ? 'permission' : 'permissions' }}{{ !group.canAssign ? ' · Restricted' : '' }}</small></span><v-icon v-if="!group.canAssign" icon="mdi-lock-outline" size="16" /></label></div><p v-if="self" class="account-footnote">Another administrator must change your own memberships here.</p><p v-if="!draft.groups.length" class="account-footnote">This account has no group-granted permissions.</p><details class="account-permissions"><summary>{{ dirty ? 'Draft' : 'Saved' }} combined permissions · {{ draftPermissions.length }}</summary><ul><li v-for="permission in draftPermissions" :key="permission">{{ permission }}</li></ul><p v-if="!draftPermissions.length">No permissions granted by these groups.</p></details><div v-if="groupsChanged" class="account-impact-note"><v-icon icon="mdi-shield-account-outline" /><p>Saving membership changes ends existing sign-in sessions. The next sign-in uses the new group access.</p></div></section>
        </div><aside class="account-context-column"><section class="account-context-card"><span class="account-eyebrow">Account context</span><dl><div><dt>Sign-in provider</dt><dd>{{ saved.providerTitle }}</dd></div><div><dt>Created</dt><dd>{{ date(saved.createdAt) }}</dd></div><div><dt>Profile last changed</dt><dd>{{ date(saved.updatedAt) }}</dd></div><div><dt>Last sign-in or renewal</dt><dd>{{ saved.lastLoginAt ? date(saved.lastLoginAt) : 'Not recorded' }}</dd></div></dl><p>Renewals update this timestamp. It is not a live presence indicator.</p></section><section class="account-context-card"><span class="account-eyebrow">Contributions</span><dl class="account-contributions"><div><dt>Pages created</dt><dd>{{ saved.contributionCounts.pagesCreated }}</dd></div><div><dt>Pages last authored</dt><dd>{{ saved.contributionCounts.pagesAuthored }}</dd></div><div><dt>Local comments</dt><dd>{{ saved.contributionCounts.comments }}</dd></div><div><dt>Assets attributed</dt><dd>{{ saved.contributionCounts.assets }}</dd></div></dl><p>These are current attribution counts, not a complete activity history.</p><div v-if="saved.privateOwnershipBlocksDeletion" class="account-private-note"><v-icon icon="mdi-lock-outline" size="17" />Private page ownership or history prevents deletion.</div></section></aside></div>
        <div v-if="saved.capabilities.edit" class="account-draft-bar"><div><strong>{{ dirty ? changes.length + (changes.length === 1 ? ' field changed' : ' fields changed') : 'Profile matches the saved account' }}</strong><span>Review changes before they affect this person.</span></div><div><v-btn variant="text" :disabled="!dirty || busy || dialog" @click="reset">Reset draft</v-btn><v-btn color="primary" variant="flat" :disabled="!dirty || busy || profileIssues.length > 0" @click="open('profile')">Review profile changes</v-btn></div></div>
        <v-alert v-if="dirty && profileIssues.length" type="warning" variant="tonal" class="mt-4"><ul><li v-for="issue in profileIssues" :key="issue">{{ issue }}</li></ul></v-alert>
      </section>
      <section v-show="section === 'security'" id="account-panel-security" role="tabpanel" aria-labelledby="account-tab-security">
        <div class="account-section-heading"><div><span class="account-eyebrow">Sign-in & security</span><h3>Sign-in controls</h3><p>Review each action and its effects before applying it to the saved account.</p></div><v-btn to="/auth" variant="text" append-icon="mdi-arrow-top-right">Authentication settings</v-btn></div>
        <v-alert v-if="dirty" type="info" variant="tonal" class="mb-5">Security actions are paused while you have unsaved profile changes.<v-btn variant="text" @click="setSection('profile')">Return to profile</v-btn></v-alert>
        <div class="account-security-grid"><section class="account-security-card"><v-icon icon="mdi-login" size="26" /><span class="account-eyebrow">Account availability</span><h4>{{ saved.isActive ? 'Open for sign-in' : 'Sign-in is suspended' }}</h4><p>{{ saved.isActive ? 'The account is active. Provider, verification and authenticator policies still apply.' : 'This person cannot sign in. Their profile, memberships and contributions are retained.' }}</p><v-btn v-if="can('deactivate')" variant="outlined" :disabled="actionLocked" @click="open('deactivate')">Deactivate account</v-btn><v-btn v-if="can('activate')" variant="outlined" :disabled="actionLocked" @click="open('activate')">Activate account</v-btn><small v-if="!can('deactivate') && !can('activate')">Availability is protected for this account.</small></section>
          <section class="account-security-card"><v-icon icon="mdi-email-check-outline" size="26" /><span class="account-eyebrow">Email ownership</span><h4>{{ saved.isVerified ? 'Address is verified' : 'Address needs verification' }}</h4><p>{{ saved.isVerified ? 'The account is marked as having a verified email address.' : 'Confirm that this person controls the address before marking it verified.' }}</p><v-btn v-if="can('verify')" variant="outlined" :disabled="actionLocked" @click="open('verify')">Verify email address</v-btn><small v-else>Changing the address clears this status.</small></section>
          <section class="account-security-card"><v-icon icon="mdi-two-factor-authentication" size="26" /><span class="account-eyebrow">Authenticator</span><h4>{{ twoFactorTitle }}</h4><p>{{ twoFactorDescription }}</p><div class="account-security-actions"><v-btn v-if="can('require-2fa')" variant="outlined" :disabled="actionLocked" @click="open('require-2fa')">Require enrollment</v-btn><v-btn v-if="can('reset-2fa')" variant="outlined" :disabled="actionLocked" @click="open('reset-2fa')">Reset authenticator</v-btn><v-btn v-if="can('disable-2fa')" variant="text" :disabled="actionLocked" @click="open('disable-2fa')">Remove account requirement</v-btn></div></section>
          <section class="account-security-card"><v-icon icon="mdi-key-outline" size="26" /><span class="account-eyebrow">Password</span><h4>{{ saved.provider?.localPassword ? saved.mustChangePassword ? 'Change required at sign-in' : 'Managed by this workspace' : 'Managed by the identity provider' }}</h4><p>{{ saved.provider?.localPassword ? 'A replacement password ends existing sessions and invalidates pending recovery links. You can require the person to choose their own at the next sign-in.' : 'Manage credentials in ' + saved.providerTitle + '. This workspace does not store or replace that provider’s password.' }}</p><v-btn v-if="saved.capabilities.password" variant="outlined" :disabled="actionLocked" @click="open('password')">Replace password</v-btn><v-btn v-else-if="self && saved.provider?.localPassword" href="/p" variant="outlined">Open my profile</v-btn></section>
          <section class="account-security-card"><v-icon icon="mdi-devices" size="26" /><span class="account-eyebrow">Sign-in sessions</span><h4>Require a fresh sign-in</h4><p>Invalidate existing sign-in tokens and pending recovery or sign-in links. People can sign in again with their current credentials.</p><small>Last ended: {{ saved.sessionsRevokedAt ? date(saved.sessionsRevokedAt) : 'Not recorded' }}. Individual devices are not tracked here.</small><v-btn v-if="can('end-sessions')" variant="outlined" :disabled="actionLocked" @click="open('end-sessions')">End sign-in sessions</v-btn><p class="account-footnote">Workspace API keys have their own lifecycle in <router-link to="/api">API access</router-link>.</p></section>
          <section class="account-security-card"><v-icon icon="mdi-email-fast-outline" size="26" /><span class="account-eyebrow">Welcome email</span><h4>A useful first step</h4><p>Send the workspace’s welcome message and a link to sign in. It contains no password or verification token.</p><small>Sending uses the saved address. Mail acceptance does not confirm delivery.</small><v-btn v-if="saved.capabilities.edit && saved.isActive" variant="outlined" :disabled="actionLocked" @click="open('welcome')">Review welcome email</v-btn></section>
        </div>
        <section class="account-deletion"><div><span class="account-eyebrow">Account retirement</span><h4>Delete this account</h4><p>Remove the account and its sign-in recovery keys. Contribution attribution must move to another active person.</p><p v-if="!saved.capabilities.delete" class="account-footnote">{{ saved.capabilities.explanation || 'Deletion is unavailable for this account.' }}</p></div><v-btn v-if="saved.capabilities.delete" color="error" variant="outlined" :disabled="actionLocked" @click="open('delete')">Review deletion</v-btn></section>
      </section>
      <section v-show="section === 'activity'" id="account-panel-activity" role="tabpanel" aria-labelledby="account-tab-activity"><div class="account-section-heading"><div><span class="account-eyebrow">Administrative history</span><h3>A record of considered changes.</h3><p>The latest 50 recorded account actions. Reasons are visible to administrators; passwords and authenticator secrets are never included.</p></div></div><async-state v-if="!saved.history.length" state="empty" title="No administrative actions recorded yet" message="New changes made through this workspace and the administration API will appear here. Earlier activity is not reconstructed." /><ol v-else class="account-activity"><li v-for="event in saved.history" :key="event.id"><span class="account-event-dot" aria-hidden="true" /><div><div class="account-event-heading"><h4>{{ eventTitle(event.action) }}</h4><time :datetime="event.createdAt">{{ date(event.createdAt) }}</time></div><small>{{ event.actorId ? 'Administrator account #' + event.actorId : 'Workspace credential' }}</small><p>{{ event.reason }}</p><ul v-if="eventFields(event.details).length"><li v-for="field in eventFields(event.details)" :key="field">{{ field }}</li></ul></div></li></ol></section>
    </template>
    <v-dialog v-model="dialog" max-width="760" :persistent="busy" :aria-label="dialogTitle"><v-card class="account-review-dialog"><v-card-title><span class="account-eyebrow">Account #{{ saved?.id }} · Review</span><h2>{{ dialogTitle }}</h2></v-card-title><v-card-text v-if="saved"><div class="account-review-person"><strong>{{ saved.name }}</strong><span>{{ saved.email }}</span></div><p class="account-review-description">{{ dialogDescription }}</p>
      <dl v-if="operation === 'profile'" class="account-review-changes"><div v-for="change in changes" :key="change.key"><dt>{{ change.title }}</dt><dd><span>{{ change.before || 'Empty' }}</span><v-icon icon="mdi-arrow-right" size="16" /><strong>{{ change.after || 'Empty' }}</strong></dd></div></dl>
      <template v-if="operation === 'password'"><v-text-field v-model="password" label="New temporary password" :type="showPassword ? 'text' : 'password'" autocomplete="new-password" variant="outlined" hint="At least 12 characters; at most 72 UTF-8 bytes." persistent-hint :disabled="busy"><template #append-inner><v-btn variant="text" size="small" :icon="showPassword ? 'mdi-eye-off-outline' : 'mdi-eye-outline'" :aria-label="showPassword ? 'Hide new password' : 'Show new password'" @click="showPassword = !showPassword" /></template></v-text-field><v-checkbox v-model="mustChangePassword" label="Require a different password at the next sign-in" hide-details :disabled="busy" /></template>
      <template v-if="operation === 'delete'"><v-alert type="warning" variant="tonal" class="mb-4">Deletion is permanent. Deactivation preserves the account and is reversible.</v-alert><dl class="account-delete-counts"><div><dt>Pages created</dt><dd>{{ saved.contributionCounts.pagesCreated }}</dd></div><div><dt>Pages last authored</dt><dd>{{ saved.contributionCounts.pagesAuthored }}</dd></div><div><dt>Local comments</dt><dd>{{ saved.contributionCounts.comments }}</dd></div><div><dt>Assets</dt><dd>{{ saved.contributionCounts.assets }}</dd></div></dl><v-autocomplete v-model="replaceId" v-model:search="replacementSearch" :items="replacementOptions" label="Reassign contribution attribution to" item-title="title" item-value="id" variant="outlined" :loading="replacementLoading" :disabled="busy" no-filter clearable hide-no-data hint="Search for another active account in your administrative scope." persistent-hint @update:search="searchReplacements" /><v-alert v-if="replacementError" type="error" variant="tonal" class="my-3">{{ replacementError }}<v-btn variant="text" @click="searchReplacements">Try again</v-btn></v-alert><v-text-field v-model="deleteConfirmation" :label="`Type ${saved.id} to confirm account deletion`" variant="outlined" class="mt-4" autocomplete="off" :disabled="busy" /></template>
      <v-alert v-if="endsOwnSessions" type="warning" variant="tonal" class="my-4">This also ends your current sign-in. You will return to the sign-in page.</v-alert>
      <v-textarea v-model="reason" label="Administrative reason" variant="outlined" rows="2" auto-grow maxlength="1000" class="mt-5" :disabled="busy" hint="3–1,000 characters. Do not include credentials or private recovery information." persistent-hint />
      <v-alert v-if="actionError" type="error" variant="tonal" class="mt-4">{{ actionError }}<v-btn v-if="conflict" variant="text" :disabled="busy" @click="reloadReview">Reload account</v-btn></v-alert>
    </v-card-text><v-card-actions><v-btn variant="text" :disabled="busy" @click="dialog = false; password = ''">{{ operation === 'profile' ? 'Keep editing' : 'Cancel' }}</v-btn><v-spacer /><v-btn :color="operation === 'delete' ? 'error' : 'primary'" variant="flat" :disabled="!canConfirm || conflict" :loading="busy" @click="confirm">{{ operation === 'profile' ? 'Save profile changes' : operation === 'welcome' ? 'Send welcome email' : dialogTitle }}</v-btn></v-card-actions></v-card></v-dialog>
  </v-container>
</template>
<script lang="ts">
import AsyncState from '@/components/common/async-state.vue'
import { accountActionTitle, accountProfileIssues, type AccountAction, type AccountProfileDraft, type AccountWorkspace } from '../../../shared/account-policy.ts'
import { fetchAccount, fetchAccountDirectory, saveAccountProfile, actOnAccount, replaceAccountPassword, deleteAccount, sendAccountWelcomeEmail, accountRequestStatus } from '../../helpers/account-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
import { wikiStore } from '@/store/index.ts'
type Operation = AccountAction | 'profile' | 'password' | 'delete' | 'welcome'
const copy = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T
const fieldTitles: Record<keyof AccountProfileDraft, string> = { name: 'Display name', email: 'Email address', jobTitle: 'Role or job title', location: 'Location', timezone: 'Time zone', groups: 'Group membership' }
const descriptions: Record<AccountAction, string> = {
  activate: 'Allow this person to sign in again under the provider’s current policies. Existing revoked sessions stay invalid.', deactivate: 'Suspend sign-in and end existing sessions. The account, memberships and contributions remain available for future reactivation.', verify: 'Mark the saved email address as verified after confirming that this person controls it. This action does not send a verification link.', 'require-2fa': 'Require authenticator enrollment during the next supported sign-in and end existing sessions. Any unfinished setup is cleared.', 'reset-2fa': 'Clear the current authenticator and require fresh enrollment at the next sign-in. Existing sessions will end. Confirm the person’s identity before proceeding.', 'disable-2fa': 'Remove this account’s authenticator and its account-specific requirement, then end existing sessions. This action is unavailable while the workspace requires two-factor authentication.', 'end-sessions': 'Invalidate existing sign-in tokens and pending recovery or sign-in links for this account. Current credentials remain usable for a new sign-in. Workspace API keys are unaffected.' }
export default {
  components: { AsyncState },
  data() { return { saved: null as AccountWorkspace | null, draft: { name: '', email: '', location: '', jobTitle: '', timezone: 'UTC', groups: [] } as AccountProfileDraft, loading: false, loadError: '', sequence: 0, disposed: false, notice: '', section: 'profile', tabs: [{ key: 'profile', title: 'Profile & membership' }, { key: 'security', title: 'Sign-in & security' }, { key: 'activity', title: 'Activity' }], dialog: false, operation: 'profile' as Operation, reason: '', password: '', showPassword: false, mustChangePassword: true, busy: false, actionError: '', conflict: false, replacementSearch: '', replaceId: null as number | null, replacementOptions: [] as Array<{ id: number; title: string }>, replacementLoading: false, replacementError: '', replacementSequence: 0, replacementTimer: null as ReturnType<typeof setTimeout> | null, deleteConfirmation: '' } },
  computed: {
    directoryPath(): string { const from = this.$route.query.from; return typeof from === 'string' && (from === '/users' || from.startsWith('/users?')) ? from : '/users' },
    self(): boolean { return this.saved?.id === wikiStore.user.id },
    dirty(): boolean { return Boolean(this.saved && JSON.stringify({ ...this.draft, groups: [...this.draft.groups].sort((a,b) => a-b) }) !== JSON.stringify(this.saved.profile)) },
    emailChanged(): boolean { return Boolean(this.saved && this.draft.email.trim().toLowerCase() !== this.saved.email) },
    groupsChanged(): boolean { return Boolean(this.saved && JSON.stringify([...this.draft.groups].sort((a,b) => a-b)) !== JSON.stringify(this.saved.profile.groups)) },
    profileLocked(): boolean { return this.busy || this.dialog || !this.saved?.capabilities.edit },
    actionLocked(): boolean { return this.dirty || this.busy || this.dialog },
    profileIssues() { return accountProfileIssues(this.draft) },
    draftPermissions() { return [...new Set((this.saved?.availableGroups ?? []).filter(group => this.draft.groups.includes(group.id)).flatMap(group => group.permissions))].sort() },
    changes(): Array<{ key: string; title: string; before: string; after: string }> { if (!this.saved) return []; return (Object.keys(fieldTitles) as Array<keyof AccountProfileDraft>).flatMap(key => { const before = this.saved!.profile[key], after = this.draft[key]; if (key === 'groups' ? !this.groupsChanged : before === after) return []; const value = (input: string | number[]) => Array.isArray(input) ? input.map(id => this.saved?.availableGroups.find(group => group.id === id)?.name ?? '#' + id).join(', ') : input; return [{ key, title: fieldTitles[key], before: value(before), after: value(after) }] }) },
    twoFactorTitle(): string { return ({ enrolled: 'Authenticator enrolled', 'enrollment-required': 'Enrollment required', off: 'No account requirement', 'provider-managed': 'Managed by the provider' })[this.saved?.twoFactor ?? 'off'] },
    twoFactorDescription(): string { return ({ enrolled: 'An authenticator is enrolled for this account’s supported sign-in flow.', 'enrollment-required': 'This person must complete authenticator enrollment during their next supported sign-in.', off: 'This account does not currently require an authenticator in the workspace.', 'provider-managed': 'This provider handles its own sign-in challenges. Check the identity provider for its authentication policies.' })[this.saved?.twoFactor ?? 'off'] },
    dialogTitle(): string { return this.operation === 'profile' ? 'Review profile changes' : this.operation === 'password' ? 'Replace password' : this.operation === 'delete' ? 'Delete account' : this.operation === 'welcome' ? 'Send a welcome email' : accountActionTitle[this.operation] },
    dialogDescription(): string { return this.operation === 'profile' ? 'Apply the following changes to the saved account. Group or email changes end existing sign-in sessions.' : this.operation === 'password' ? 'Set a new local password and end existing sign-in sessions. Share it privately; the welcome email never contains a password.' : this.operation === 'delete' ? 'Private pages and history owned by this account must be resolved before deletion. Existing authorship and creation attribution will move to the selected person; content remains.' : this.operation === 'welcome' ? 'Send the configured workspace welcome template to this saved email address, including a link to sign in. This does not create a password, verify ownership or bypass sign-in requirements.' : descriptions[this.operation] },
    endsOwnSessions(): boolean { return this.self && (this.operation === 'profile' ? this.emailChanged || this.groupsChanged : !['activate', 'verify', 'welcome', 'delete'].includes(this.operation)) },
    canConfirm(): boolean { if (this.busy || this.reason.trim().length < 3 || this.reason.trim().length > 1000) return false; if (this.operation === 'profile') return this.dirty && this.profileIssues.length === 0; if (this.operation === 'password') return this.password.length >= 12 && new TextEncoder().encode(this.password).length <= 72; if (this.operation === 'delete') return Boolean(this.replaceId && this.deleteConfirmation === String(this.saved?.id)); return true }
  },
  methods: {
    async reload() { if (this.busy || (this.dirty && !window.confirm('Discard unsaved profile changes and reload this account?'))) return; const sequence = ++this.sequence; this.loading = true; this.loadError = ''; this.saved = null; try { const value = await fetchAccount(Number(this.$route.params.id)); if (!this.disposed && sequence === this.sequence) { this.saved = value; this.draft = copy(value.profile) } } catch (error) { if (!this.disposed && sequence === this.sequence) this.loadError = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } },
    reset() { if (this.saved && !this.busy && !this.dialog) this.draft = copy(this.saved.profile) },
    can(action: AccountAction): boolean { return this.saved?.capabilities.actions.includes(action) ?? false },
    open(operation: Operation) { if (this.busy || (operation !== 'profile' && this.dirty)) return; this.operation = operation; this.reason = ''; this.password = ''; this.showPassword = false; this.mustChangePassword = true; this.actionError = ''; this.conflict = false; this.deleteConfirmation = ''; this.replaceId = null; this.replacementSearch = ''; this.replacementOptions = []; this.dialog = true; if (operation === 'delete') this.searchReplacements() },
    async reloadReview() { this.dialog = false; this.password = ''; await this.reload() },
    async confirm() { if (!this.saved || !this.canConfirm) return; const id = this.saved.id, operation = this.operation, ownSessions = this.endsOwnSessions; this.busy = true; this.actionError = ''; try { let next: AccountWorkspace | null = null; if (operation === 'profile') next = await saveAccountProfile(id, copy(this.draft), this.reason.trim(), this.saved.fingerprint); else if (operation === 'password') next = await replaceAccountPassword(id, this.password, this.mustChangePassword, this.reason.trim(), this.saved.fingerprint); else if (operation === 'delete') { await deleteAccount(id, this.replaceId!, this.reason.trim(), this.saved.fingerprint); this.dialog = false; this.busy = false; this.draft = copy(this.saved.profile); await this.$router.push(this.directoryPath); return } else if (operation === 'welcome') { await sendAccountWelcomeEmail(id, this.reason.trim(), this.saved.fingerprint); this.notice = 'Welcome email accepted by the mail service. Delivery is not confirmed.'; try { next = await fetchAccount(id) } catch { this.notice += ' Reload to refresh account history.' } } else next = await actOnAccount(id, operation, this.reason.trim(), this.saved.fingerprint); if (this.disposed) return; if (next) { this.saved = next; this.draft = copy(next.profile); if (operation !== 'welcome') this.notice = operation === 'profile' ? 'Profile changes saved.' : this.dialogTitle + ' completed.' } this.dialog = false; this.password = ''; if (ownSessions) window.location.assign('/login') } catch (error) { if (!this.disposed) { this.conflict = accountRequestStatus(error) === 409; this.actionError = getErrorMessage(error) + (accountRequestStatus(error) === 0 ? ' The outcome is unconfirmed. Reload the account before repeating this action.' : '') } } finally { if (!this.disposed) this.busy = false } },
    searchReplacements() { if (this.replacementTimer) clearTimeout(this.replacementTimer); const sequence = ++this.replacementSequence, search = this.replacementSearch || ''; this.replacementTimer = setTimeout(async () => { this.replacementLoading = true; this.replacementError = ''; try { const value = await fetchAccountDirectory(new URLSearchParams({ search, state: 'active', limit: '25' })); if (!this.disposed && sequence === this.replacementSequence) this.replacementOptions = value.items.filter(row => row.id !== this.saved?.id && row.id !== 2 && row.groups.every(group => this.saved?.availableGroups.some(option => option.id === group.id && option.canAssign))).map(row => ({ id: row.id, title: `${row.name} · ${row.email}` })) } catch (error) { if (!this.disposed && sequence === this.replacementSequence) this.replacementError = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.replacementSequence) this.replacementLoading = false } }, 250) },
    setSection(key: string) { this.section = key; void this.$router.replace({ query: this.$route.query, hash: '#' + key }) },
    tabKey(event: KeyboardEvent, key: string) { if (!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) return; event.preventDefault(); const index = event.key === 'Home' ? 0 : event.key === 'End' ? this.tabs.length - 1 : (this.tabs.findIndex(tab => tab.key === key) + (event.key === 'ArrowRight' ? 1 : -1) + this.tabs.length) % this.tabs.length; const next = this.tabs[index]!.key; this.setSection(next); this.$nextTick(() => document.getElementById('account-tab-' + next)?.focus()) },
    initials(value: string) { return value.trim().split(/\s+/).slice(0,2).map(part => part[0]).join('').toUpperCase() },
    date(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? 'Not recorded' : date.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) },
    eventTitle(action: string): string { return (accountActionTitle as Record<string,string>)[action] ?? ({ 'profile-updated': 'Profile updated', 'membership-updated': 'Group membership changed', 'group-policy-updated': 'Group access policy changed', 'group-deleted': 'Group membership ended after deletion', 'account-created': 'Account created', 'account-deleted': 'Account deleted', 'password-replaced': 'Password replaced', 'welcome-email-requested': 'Welcome email requested · outcome not recorded', 'welcome-email-accepted': 'Welcome email accepted by mail service', 'welcome-email-failed': 'Welcome email failed' } as Record<string,string>)[action] ?? action },
    eventFields(details: Record<string,unknown>): string[] { const fields = Array.isArray(details.fields) ? details.fields.filter((value): value is string => typeof value === 'string').map(value => fieldTitles[value as keyof AccountProfileDraft] ?? value) : []; return [...fields, ...(typeof details.groupId === 'number' ? ['Group #' + details.groupId] : []), ...(details.sessionsEnded === true ? ['Existing sign-in sessions ended'] : [])] },
    canLeave(): boolean { return !this.busy && ((!this.dirty && !(this.dialog && (this.password || this.reason))) || window.confirm('Discard the unsaved account changes?')) },
    beforeUnload(event: BeforeUnloadEvent) { if (this.dirty || this.busy || (this.dialog && (this.password || this.reason))) { event.preventDefault(); event.returnValue = '' } }
  },
  watch: { '$route.hash': { immediate: true, handler(hash: string) { this.section = this.tabs.some(tab => tab.key === hash.slice(1)) ? hash.slice(1) : 'profile' } }, '$route.params.id'() { if (this.saved) this.draft = copy(this.saved.profile); this.dialog = false; this.password = ''; this.notice = ''; void this.reload() }, dialog(value: boolean) { if (!value) { this.password = ''; this.replacementSequence++; if (this.replacementTimer) clearTimeout(this.replacementTimer) } } },
  mounted() { void this.reload(); window.addEventListener('beforeunload', this.beforeUnload) },
  beforeRouteLeave() { return this.canLeave() },
  beforeRouteUpdate(to, from) { return to.params.id === from.params.id || this.canLeave() },
  beforeUnmount() { this.disposed = true; this.sequence++; this.replacementSequence++; if (this.replacementTimer) clearTimeout(this.replacementTimer); this.password = ''; window.removeEventListener('beforeunload', this.beforeUnload) }
}
</script>
<style lang="scss">
.account-workspace,.account-review-dialog { --account-line:rgba(var(--v-theme-on-surface),.12); --account-muted:rgba(var(--v-theme-on-surface),.68); .account-eyebrow { display:block; font-size:.66rem; letter-spacing:.12em; text-transform:uppercase; font-weight:650; color:var(--account-muted); } }
.account-workspace .admin-hero__description { overflow-wrap:anywhere; }
.account-identity { display:flex; gap:16px; align-items:center; padding:12px 0 22px; }
.account-portrait { display:grid; place-items:center; width:44px; height:44px; flex-shrink:0; border:1px solid rgba(var(--v-theme-primary),.28); background:rgba(var(--v-theme-primary),.08); border-radius:50%; font-size:.9rem; letter-spacing:-.02em; }
.account-identity-name { min-width:0; h2 { margin:6px 0; font-size:1.85rem; letter-spacing:-.035em; font-weight:500; line-height:1.2; overflow-wrap:anywhere; } p { margin:6px 0 0; font-size:.84rem; color:var(--account-muted); overflow-wrap:anywhere; } }
.account-identity-status { margin-left:auto; display:flex; align-items:flex-end; flex-direction:column; gap:9px; span { display:flex; align-items:center; gap:7px; font-size:.83rem; } i { width:7px; height:7px; background:rgb(var(--v-theme-success)); border-radius:50%; &.paused { background:rgba(var(--v-theme-on-surface),.4); } } small { font-size:.72rem; color:var(--account-muted); } }
.account-tabs-row { display:flex; justify-content:space-between; gap:18px; align-items:center; border-bottom:1px solid var(--account-line); margin-bottom:26px; >span { font-size:.72rem; color:var(--account-muted); } }
.account-tabs { display:flex; gap:25px; button { background:transparent; border:0; border-bottom:3px solid transparent; color:var(--account-muted); padding:15px 0; cursor:pointer; font-size:.81rem; font-weight:550; &[aria-selected=true] { border-bottom-color:rgb(var(--v-theme-primary)); color:rgb(var(--v-theme-on-surface)); } &:focus-visible { outline:2px solid rgb(var(--v-theme-on-surface)); outline-offset:4px; } } }
.account-profile-layout { display:grid; grid-template-columns:minmax(0,1fr) 260px; gap:24px; align-items:start; }
.account-main-column { display:grid; gap:22px; min-width:0; }
.account-surface { padding:26px; border:1px solid var(--account-line); border-radius:12px; background:rgb(var(--v-theme-surface)); header { margin-bottom:24px; h3 { margin:7px 0 8px; font-size:1.2rem; font-weight:500; letter-spacing:-.02em; } p { margin:0; font-size:.8rem; line-height:1.7; color:var(--account-muted); max-width:620px; } } }
.account-profile-form { display:grid; grid-template-columns:1fr 1fr; gap:4px 18px; >* { min-width:0; } }
.account-impact-note { display:flex; align-items:flex-start; gap:12px; padding:16px; background:rgba(var(--v-theme-primary),.06); border-left:2px solid rgb(var(--v-theme-primary)); margin-top:18px; p { margin:0; font-size:.8rem; line-height:1.6; } }
.account-membership-grid { display:grid; grid-template-columns:1fr 1fr; gap:10px; label { border:1px solid var(--account-line); border-radius:8px; display:flex; gap:12px; align-items:flex-start; padding:15px; cursor:pointer; min-width:0; &.selected { border-color:rgba(var(--v-theme-primary),.6); background:rgba(var(--v-theme-primary),.04); } &.locked { cursor:default; } input { margin-top:3px; width:16px; height:16px; flex-shrink:0; accent-color:rgb(var(--v-theme-primary)); } span { min-width:0; } strong { display:block; font-size:.8rem; font-weight:600; overflow-wrap:anywhere; } small { display:block; font-size:.68rem; margin-top:5px; color:var(--account-muted); } } }
.account-permissions { margin-top:20px; summary { font-size:.78rem; cursor:pointer; } >ul { display:flex; flex-wrap:wrap; gap:6px 18px; padding:16px 0 0; list-style:none; font-size:.73rem; } p { font-size:.76rem; margin-top:12px; color:var(--account-muted); } }
.account-context-column { display:grid; gap:22px; }
.account-context-card { padding:24px 20px; border:1px solid var(--account-line); border-radius:10px; dl { margin-top:22px; display:grid; gap:20px; } dt { font-size:.69rem; color:var(--account-muted); margin-bottom:6px; } dd { font-size:.8rem; overflow-wrap:anywhere; } >p { margin:20px 0 0; font-size:.71rem; line-height:1.6; color:var(--account-muted); } .account-contributions { gap:17px; >div { display:flex; justify-content:space-between; gap:12px; align-items:center; } dt { margin:0; } dd { font-size:1rem; font-variant-numeric:tabular-nums; } } }
.account-private-note { display:flex; gap:8px; padding-top:18px; margin-top:18px; border-top:1px solid var(--account-line); font-size:.72rem; line-height:1.6; }
.account-footnote { font-size:.74rem!important; line-height:1.65; color:var(--account-muted); margin:14px 0 0; a { color:inherit; text-underline-offset:3px; } }
.account-draft-bar { display:flex; justify-content:space-between; align-items:center; gap:20px; padding:20px 0; margin-top:5px; >div:last-child { display:flex; gap:8px; } strong { font-size:.82rem; display:block; font-weight:550; } span { display:block; font-size:.71rem; color:var(--account-muted); margin-top:5px; } }
.account-section-heading { display:flex; gap:24px; justify-content:space-between; align-items:center; padding:4px 0 25px; h3 { font-size:1.45rem; margin:8px 0 10px; font-weight:500; letter-spacing:-.025em; } p { font-size:.82rem; max-width:620px; line-height:1.65; color:var(--account-muted); margin:0; } }
.account-security-grid { display:grid; grid-template-columns:1fr 1fr; gap:20px; }
.account-security-card { display:flex; flex-direction:column; align-items:flex-start; padding:26px; border:1px solid var(--account-line); border-radius:12px; background:rgb(var(--v-theme-surface)); >.v-icon { margin-bottom:19px; color:var(--account-muted); } h4 { font-size:1.08rem; font-weight:550; margin:7px 0 10px; } >p { font-size:.8rem; line-height:1.7; color:var(--account-muted); margin:0 0 20px; } >small { font-size:.72rem; color:var(--account-muted); line-height:1.6; margin-bottom:18px; } >.v-btn,.account-security-actions { margin-top:auto; } .account-footnote { margin:14px 0 0; } }
.account-security-actions { display:flex; gap:8px; align-items:flex-start; flex-wrap:wrap; .v-btn { max-width:100%; } }
.account-deletion { margin-top:28px; border-top:1px solid var(--account-line); padding:30px 0 10px; display:flex; align-items:center; justify-content:space-between; gap:28px; h4 { font-size:1.1rem; font-weight:550; margin:8px 0; } p { font-size:.8rem; color:var(--account-muted); line-height:1.7; margin:0; max-width:650px; } }
.account-activity { list-style:none; padding:0; margin:4px 0; >li { display:grid; grid-template-columns:20px 1fr; gap:16px; padding:0 0 28px; position:relative; &::before { content:''; position:absolute; top:9px; bottom:0; left:4px; border-left:1px solid var(--account-line); } &:last-child::before { bottom:calc(100% - 10px); } >div { border:1px solid var(--account-line); border-radius:10px; padding:22px 24px; background:rgb(var(--v-theme-surface)); } small { font-size:.72rem; color:var(--account-muted); display:block; margin-top:7px; } p { font-size:.83rem; white-space:pre-wrap; overflow-wrap:anywhere; line-height:1.7; margin:16px 0 0; } ul { list-style:none; padding:0; display:flex; flex-wrap:wrap; gap:8px; margin-top:14px; li { font-size:.67rem; padding:4px 7px; border-radius:4px; background:rgba(var(--v-theme-on-surface),.045); } } } }
.account-event-dot { height:9px; width:9px; margin-top:8px; border-radius:50%; background:rgb(var(--v-theme-primary)); z-index:1; }
.account-event-heading { display:flex; justify-content:space-between; gap:20px; h4 { font-size:.92rem; font-weight:600; } time { font-size:.7rem; color:var(--account-muted); flex-shrink:0; } }
.account-review-dialog { max-height:90dvh; .v-card-title { white-space:normal; padding:26px 28px 16px; h2 { font-size:1.45rem; margin-top:7px; font-weight:500; } } .v-card-text { padding:10px 28px 26px; overflow-y:auto; } .v-card-actions { padding:16px 22px; border-top:1px solid var(--account-line); flex-wrap:wrap; } }
.account-review-person { display:flex; flex-direction:column; gap:5px; margin:0 0 18px; strong { font-size:1.1rem; font-weight:550; overflow-wrap:anywhere; } span { font-size:.83rem; color:var(--account-muted); overflow-wrap:anywhere; } }
.account-review-description { font-size:.85rem; color:var(--account-muted); line-height:1.7; margin-bottom:24px; }
.account-review-changes { display:grid; gap:18px; border-block:1px solid var(--account-line); padding:22px 0; dt { font-size:.72rem; color:var(--account-muted); margin-bottom:8px; } dd { display:flex; gap:14px; align-items:center; font-size:.85rem; overflow-wrap:anywhere; >span,>strong { flex:1; min-width:0; } >span { color:var(--account-muted); } strong { font-weight:550; } } }
.account-delete-counts { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin:22px 0; dt { font-size:.7rem; color:var(--account-muted); line-height:1.5; } dd { font-size:1.25rem; margin-top:8px; } }
@media(max-width:1100px) { .account-profile-layout { grid-template-columns:1fr; } .account-context-column { grid-template-columns:1fr 1fr; } .account-tabs-row { align-items:flex-start; flex-direction:column; gap:0; >span { padding-bottom:12px; } } }
@media(max-width:700px) { .account-identity { flex-wrap:wrap; gap:14px; padding:5px 0 20px; } .account-identity-name { flex:1; h2 { font-size:1.5rem; } } .account-identity-status { width:100%; align-items:center; flex-direction:row; flex-wrap:wrap; gap:10px 18px; margin-left:0; } .account-portrait { width:44px; height:44px; font-size:.9rem; } .account-tabs { gap:16px; width:100%; button { font-size:.73rem; } } .account-profile-form,.account-membership-grid,.account-context-column,.account-security-grid { grid-template-columns:1fr; } .account-surface,.account-security-card { padding:21px 18px; } .account-draft-bar,.account-section-heading,.account-deletion { align-items:flex-start; flex-direction:column; gap:17px; } .account-draft-bar>div:last-child { flex-wrap:wrap; } .account-security-card .v-btn { white-space:normal; height:auto; min-height:36px; padding-block:9px; .v-btn__content { white-space:normal; } } .account-event-heading { flex-direction:column; gap:8px; } .account-activity>li { gap:7px; >div { padding:18px; } } .account-review-dialog .v-card-title { padding:22px 20px 14px; } .account-review-dialog .v-card-text { padding:8px 20px 20px; } .account-delete-counts { grid-template-columns:1fr 1fr; } }
</style>
