<template>
  <section aria-labelledby="group-rules-heading"><div class="group-heading"><div><span class="group-kicker">Where page actions apply</span><h2 id="group-rules-heading">Page rules</h2><p>Describe the public pages this group may use. A rule only applies when a corresponding global permission is also granted.</p></div><v-btn v-if="!unrestricted" variant="outlined" prepend-icon="mdi-plus" :disabled="disabled || modelValue.pageRules.length >= 100" @click="open()">Add page rule</v-btn></div>
    <v-alert v-if="unrestricted" type="info" variant="tonal">Full system administration bypasses page rules. Its access is unrestricted.</v-alert>
    <template v-else><div class="group-rule-guide"><v-icon icon="mdi-sort-variant" size="21" /><p><strong>Specificity determines the result.</strong> Longer matching text wins. At equal length: exact path, tag, regular expression, suffix, then prefix. Deny wins an equal tie. <button type="button" @click="$emit('evaluate')">Try an access check <v-icon icon="mdi-arrow-right" size="16" /></button></p></div>
      <async-state v-if="!modelValue.pageRules.length" state="empty" title="No public-page rules" message="This group contributes no page-rule grants. A member’s other groups may still grant access; private ownership is separate." />
      <ol v-else class="group-rule-list"><li v-for="(rule, index) in modelValue.pageRules" :key="rule.id" class="group-rule-card"><div class="group-rule-top"><span class="group-rule-effect" :class="rule.deny ? 'is-deny' : 'is-allow'"><v-icon :icon="rule.deny ? 'mdi-minus-circle-outline' : 'mdi-check-circle-outline'" size="18" />{{ rule.deny ? 'Deny' : 'Allow' }}</span><span class="group-muted text-body-small">Rule {{ index + 1 }}</span><div class="group-actions"><v-btn icon="mdi-pencil-outline" variant="text" size="small" :aria-label="'Edit page rule ' + (index + 1)" :disabled="disabled" @click="open(rule)" /><v-btn icon="mdi-close" variant="text" size="small" :aria-label="'Remove page rule ' + (index + 1)" :disabled="disabled" @click="remove(rule.id)" /></div></div><div class="group-rule-target"><span>{{ matchTitle(rule.match) }}</span><code>{{ rule.path || 'All paths' }}</code></div><div class="group-rule-actions">{{ rule.roles.map(permissionTitle).join(' · ') }}</div><div class="group-rule-footer"><span>{{ rule.locales.length ? rule.locales.join(', ') : 'Any language' }}</span><span v-if="missingPermissions(rule).length" class="group-rule-inactive">{{ missingPermissions(rule).length }} action(s) lack a permission in this group</span></div></li></ol>
    </template>
    <v-dialog v-model="dialog" max-width="720" :fullscreen="$vuetify.display.smAndDown" :persistent="disabled" aria-labelledby="group-rule-title" @update:model-value="onClose"><v-card class="group-dialog group-rule-dialog"><div class="group-dialog-header"><h2 id="group-rule-title">{{ editingId ? 'Edit page rule' : 'Add a page rule' }}</h2><p>This changes your policy draft. Review and save the group to apply it.</p></div><v-card-text><div class="group-dialog-fields"><v-select v-model="draft.deny" :items="[{ title: 'Allow matching actions', value: false },{ title: 'Deny matching actions', value: true }]" label="Rule effect" variant="outlined" :disabled="disabled" /><v-select v-model="draft.roles" :items="actions" label="Page actions" variant="outlined" multiple chips closable-chips :disabled="disabled" /><div class="group-form-grid"><v-select v-model="draft.match" :items="matches" label="Match type" variant="outlined" :disabled="disabled" /><v-text-field v-model="draft.path" :label="draft.match === 'TAG' ? 'Tag name' : draft.match === 'REGEX' ? 'Regular expression' : 'Page path'" variant="outlined" :disabled="disabled" :hint="pathHint" persistent-hint maxlength="500" /></div><v-combobox v-model="draft.locales" label="Language codes" variant="outlined" multiple chips closable-chips hint="Leave empty for any language. For example: en, fr, pt-br." persistent-hint :disabled="disabled" /><v-alert v-if="issue" type="warning" variant="tonal">{{ issue }}</v-alert></div></v-card-text><v-card-actions><v-btn variant="text" :disabled="disabled" @click="dialog = false">Cancel</v-btn><v-spacer /><v-btn color="primary" variant="flat" :disabled="disabled || Boolean(issue)" @click="apply">Use this rule</v-btn></v-card-actions></v-card></v-dialog>
  </section>
</template>
<script lang="ts">
import { type PropType } from 'vue'
import AsyncState from '@/components/common/async-state.vue'
import { groupPermissions, type GroupPolicyDraft, type GroupPageRule, type GroupRuleMatch } from '../../../shared/group-policy.ts'
const emptyRule = (): GroupPageRule => ({ id: '', match: 'START', path: '', deny: false, roles: ['read:pages'], locales: [] })
const matches = [{ title: 'Path starts with', value: 'START' },{ title: 'Path is exactly', value: 'EXACT' },{ title: 'Path ends with', value: 'END' },{ title: 'Tag matches', value: 'TAG' },{ title: 'Regular expression', value: 'REGEX' }]
export default {
  components: { AsyncState }, props: { modelValue: { type: Object as PropType<GroupPolicyDraft>, required: true }, disabled: Boolean, unrestricted: Boolean }, emits: ['update:modelValue','evaluate','draft-state'],
  data() { return { dialog: false, editingId: '', draft: emptyRule(), original: '', matches, actions: groupPermissions.filter(p => p.pageScoped).map(p => ({ title: p.title, value: p.key })) } },
  computed: { pathHint() { return this.draft.match === 'START' ? 'No leading /. Leave empty to match every public path.' : this.draft.match === 'TAG' ? 'Renamed tags resolve through the taxonomy; archived tags do not match.' : this.draft.match === 'REGEX' ? 'Applied to the path without a leading /. Unsafe expressions are rejected when the group is saved.' : 'Enter the path without a leading /.' }, issue(): string { if (!this.draft.roles.length) return 'Choose at least one page action.'; if (['TAG','REGEX'].includes(this.draft.match) && !this.draft.path.trim()) return 'Enter a match value.'; if (this.draft.match === 'REGEX') { try { new RegExp(this.draft.path) } catch { return 'This regular expression is not valid.' } } if (this.draft.locales.some(code => typeof code !== 'string' || !/^[a-zA-Z0-9_-]{1,24}$/.test(code))) return 'Enter valid language codes.'; return '' } },
  watch: { dialog(value: boolean) { this.$emit('draft-state', value && this.original !== JSON.stringify(this.draft)) }, draft: { deep: true, handler() { this.$emit('draft-state', this.dialog && this.original !== JSON.stringify(this.draft)) } } },
  methods: { matchTitle(match: GroupRuleMatch) { return matches.find(item => item.value === match)?.title ?? match }, permissionTitle(key: string) { return groupPermissions.find(p => p.key === key)?.title ?? key }, missingPermissions(rule: GroupPageRule) { return rule.roles.filter(role => !this.modelValue.permissions.includes(role)) }, open(rule?: GroupPageRule) { if (this.disabled) return; this.editingId = rule?.id ?? ''; this.draft = rule ? JSON.parse(JSON.stringify(rule)) as GroupPageRule : { ...emptyRule(), id: crypto.randomUUID() }; this.original = JSON.stringify(this.draft); this.dialog = true }, apply() { if (this.disabled || this.issue) return; const rule: GroupPageRule = { ...this.draft, path: this.draft.path.trim(), roles: [...new Set(this.draft.roles)], locales: [...new Set(this.draft.locales)] }; const pageRules = this.editingId ? this.modelValue.pageRules.map(item => item.id === this.editingId ? rule : item) : [...this.modelValue.pageRules, rule]; this.$emit('update:modelValue', { ...this.modelValue, pageRules }); this.dialog = false }, remove(id: string) { if (!this.disabled) this.$emit('update:modelValue', { ...this.modelValue, pageRules: this.modelValue.pageRules.filter(rule => rule.id !== id) }) }, onClose() { this.$emit('draft-state', false) } }
}
</script>
